[project]
name = "mcp-fastmcp-finance-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.0.2",
    "httpx>=0.28.1",
    "pydantic>=2.12.4",
    "pyyaml>=6.0.3",
]
